### ISSUE TITLE
stratomex  duplicate columns

### ISSUE THREAD

**Issue by sgratzl** [Caleydo/caleydo_clue#26]
some columns aren't removed or appear twice

**Comment by gillhofer** [comment]
I may have found a similar one. 

Create a new graph --> add a column --> add another column --> switch order of columns --> go to Start state -> go to last state. ---> you now have 3 columns.

**Comment by mstreit** [comment]
I can confirm this. The problem is caused by switching to the start state.

**Comment by mstreit** [comment]
Didn't see the problem since the fix attempt by @sgratzl. Seems to be solved. Closing issue.
